// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2uPgphgS30JWDik3WF4-0eBQNd2iSIOg',
    appId: '1:781534915945:web:fd2bf2d2bdb794edbe61f8',
    messagingSenderId: '781534915945',
    projectId: 'remote-configue-demo1',
    authDomain: 'remote-configue-demo1.firebaseapp.com',
    storageBucket: 'remote-configue-demo1.appspot.com',
    measurementId: 'G-Z4FD9S96RM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClPiZY3g9J51qbDLxjV80Wiyg3e7Zuiqg',
    appId: '1:781534915945:android:a9cb59194e4a6928be61f8',
    messagingSenderId: '781534915945',
    projectId: 'remote-configue-demo1',
    storageBucket: 'remote-configue-demo1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYjCOD7dd-gnqF6TduNXRHOQODSReD-f0',
    appId: '1:781534915945:ios:50264a92f068edbbbe61f8',
    messagingSenderId: '781534915945',
    projectId: 'remote-configue-demo1',
    storageBucket: 'remote-configue-demo1.appspot.com',
    iosClientId:
        '781534915945-l0tkevta8s8hk8ik66smr4cbq99lg8m6.apps.googleusercontent.com',
    iosBundleId: 'com.example.remoteCongigueDemoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYjCOD7dd-gnqF6TduNXRHOQODSReD-f0',
    appId: '1:781534915945:ios:50264a92f068edbbbe61f8',
    messagingSenderId: '781534915945',
    projectId: 'remote-configue-demo1',
    storageBucket: 'remote-configue-demo1.appspot.com',
    iosClientId:
        '781534915945-l0tkevta8s8hk8ik66smr4cbq99lg8m6.apps.googleusercontent.com',
    iosBundleId: 'com.example.remoteCongigueDemoapp',
  );
}
